trigger:
- main # Inicia o pipeline em commits na branch main

pool: 'Default' # Agente self-hosted

variables:
  # --- Variáveis Específicas do Worker ---
  imageRepository: 'fiap-cloud-games-indexer-worker'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  
  # --- Variáveis de Conexão (Conforme seu ACR) ---
  tag: '$(Build.BuildId)'
  acrServiceConnection: 'ConexaoAzureContainerRegistry'
  acrLoginServer: 'acimel.azurecr.io'

stages:
- stage: Build
  displayName: 'Build da Imagem Docker'
  jobs:
  - job: BuildJob
    displayName: 'Build'
    steps:
    - task: Docker@2
      displayName: 'Build da Imagem'
      inputs:
        command: 'build'
        containerRegistry: '$(acrServiceConnection)'
        repository: '$(imageRepository)'
        dockerfile: '$(dockerfilePath)'
        tags: '$(tag)'

- stage: Push
  displayName: 'Push da Imagem para o ACR'
  dependsOn: Build
  jobs:
  - job: PushJob
    displayName: 'Push'
    steps:
    - task: Docker@2
      displayName: 'Push da Imagem'
      inputs:
        command: 'push'
        containerRegistry: '$(acrServiceConnection)'
        repository: '$(imageRepository)'
        tags: '$(tag)'